import {PageHero} from '@/components/PageHero';
import {CheckCircle2,Mail,Clock3,ArrowRight,Lightbulb,SearchCheck,MapPinned,MessageCircle} from 'lucide-react';
import {Reveal} from '@/components/Reveal';
import {FAQSection, FAQItem} from '@/components/FAQSection';
import {pageMetadata} from '@/lib/seo';

export const metadata=pageMetadata({title:'Contact FahadDev — Start a Web Project',description:'Send your project goal, current problem or website. Contact FahadDev by project brief, email or WhatsApp to discuss the clearest next step.',path:'/contact'});
const faqs:FAQItem[]=[
 {q:'What should I send in the first message?',a:'The current URL or idea, what is not working, who the product is for and what result matters most. Screenshots, examples and deadlines are useful when available.'},
 {q:'Do I need to know the technology I want?',a:'No. The technology should follow the product requirements, existing systems and ownership needs rather than being chosen before the problem is understood.'},
 {q:'Can I contact you on WhatsApp instead of filling the form?',a:'Yes. WhatsApp is available for a direct first conversation at +92 325 5504461.'},
 {q:'Can I ask about a small job?',a:'Yes. Focused responsive fixes, integrations, feature work, deployment help and other small technical jobs can be discussed when the problem is specific.'},
 {q:'Can I send an existing website for review?',a:'Yes. Send the URL and tell me what feels wrong from the business side — conversion, speed, mobile behavior, content control, workflow or another issue.'},
 {q:'Will I get a price immediately?',a:'A useful price depends on scope. The first step is understanding what needs to change and what can stay. Once the work is clear, pricing can be tied to actual deliverables.'},
 {q:'Can you work remotely with clients outside Pakistan?',a:'Yes. The development workflow is remote-friendly and project communication can be handled online.'},
 {q:'How quickly will you reply?',a:'The target is to reply to project messages within 24 hours when possible. Urgent context should be mentioned clearly in the first message.'},
 {q:'What happens after I send the brief?',a:'The next step is usually a reply with clarifying questions, a suggested route or a request for the specific information needed to scope the work properly.'},
 {q:'Is the first conversation a commitment to hire?',a:'No. The purpose of the first conversation is to understand the problem and whether the project is a sensible fit.'},
];
export default function Contact(){return <>
<PageHero kind="contact" eyebrow="Start with the outcome" title="Tell me what needs to work better. I’ll help you identify the clearest next step." body="You do not need a perfect technical brief. Bring the idea, existing site, broken workflow or result you need — and we can shape the right level of work from there." primary={{label:'Chat on WhatsApp',href:'https://wa.me/923255504461',external:true}} secondary={{label:'Send Project Details',href:'#project-brief'}}/>
<Reveal><section className="section shell contact-prep"><article><Lightbulb/><h3>Bring the goal</h3><p>What should customers or your team be able to do better?</p></article><article><SearchCheck/><h3>Bring the friction</h3><p>What is slow, confusing, repetitive, broken or hard to manage today?</p></article><article><MapPinned/><h3>Leave with a route</h3><p>The first useful outcome is clarity on the next step, not pressure to buy a package.</p></article></section></Reveal>
<Reveal><section id="project-brief" className="section shell contact-section"><div className="contact-side"><span className="eyebrow">Choose the easiest route</span><h2>Direct contact without oversized cards or unnecessary steps.</h2><div className="contact-channel-grid"><a className="contact-channel whatsapp" href="https://wa.me/923255504461" target="_blank" rel="noreferrer"><MessageCircle/><span><b>WhatsApp</b><small>+92 325 5504461</small></span><ArrowRight/></a><a className="contact-channel" href="mailto:hello@fahaddev.com"><Mail/><span><b>Email</b><small>hello@fahaddev.com</small></span><ArrowRight/></a><div className="contact-channel contact-response"><Clock3/><span><b>Response target</b><small>Within 24 hours</small></span></div></div><div className="contact-points"><p><CheckCircle2/><span><b>Send the context.</b> What you have, what is not working and what result matters.</span></p><p><CheckCircle2/><span><b>I’ll identify the likely route.</b> That may be a focused fix, an improvement pass or a larger build.</span></p><p><CheckCircle2/><span><b>Scope comes before commitment.</b> Deliverables and priorities are made clear before work begins.</span></p></div></div>
<form className="contact-form" action="mailto:hello@fahaddev.com" method="post" encType="text/plain"><div className="contact-form-heading"><span className="eyebrow">Project brief</span><h3>Give me enough context to make the first reply useful.</h3><p>No technical language required.</p></div><div className="form-two"><label>Name<input name="name" required placeholder="Your name"/></label><label>Email<input name="email" type="email" required placeholder="you@company.com"/></label></div><label>What needs to work better?<select name="project"><option>New e-commerce / website</option><option>Dashboard or internal tool</option><option>Full-stack web app</option><option>Fix or improve an existing product</option><option>Quick technical work</option><option>Not sure yet</option></select></label><label>Project size<select name="budget"><option>Prefer to discuss after scope</option><option>Small focused job</option><option>Medium project</option><option>Larger build</option></select></label><label>What is happening now?<textarea name="message" rows={6} placeholder="What do you have today, what is the problem, and what would a good result look like?" required/></label><button className="btn" type="submit">Send Project Brief <ArrowRight size={17}/></button><p className="form-note">Prefer chat? Use WhatsApp above for a direct conversation.</p></form></section></Reveal>
<FAQSection items={faqs} eyebrow="Before you message" title="Everything you may want to know before starting the conversation." schema/>
</>}
