import type {Metadata} from 'next';
import {PageHero} from '@/components/PageHero';
import {CheckCircle2,Mail,Clock3,ArrowRight,Lightbulb,SearchCheck,MapPinned,MessageCircle} from 'lucide-react';
import {Reveal} from '@/components/Reveal';
export const metadata:Metadata={title:'Contact — Start a Project with FahadDev',description:'Share the product, problem or workflow you want to improve. Contact FahadDev by form, email or WhatsApp.'};
export default function Contact(){return <><PageHero kind="contact" eyebrow="Start with the outcome" title="Tell me what needs to work better. We’ll map the clearest route forward." body="You do not need a perfect technical brief. Bring the idea, the broken workflow, the current site, or the result you need — and we can shape the right level of work from there." secondary="See How Delivery Works" secondaryHref="/process" primary="Get a Free Consultation"/>
<Reveal><section className="section shell contact-prep"><article><Lightbulb/><h3>Bring the goal</h3><p>What should customers or your team be able to do better?</p></article><article><SearchCheck/><h3>Bring the friction</h3><p>What is slow, confusing, repetitive, broken or hard to manage today?</p></article><article><MapPinned/><h3>Leave with a route</h3><p>The first useful outcome is clarity on the next step, not pressure to buy a package.</p></article></section></Reveal>
<Reveal><section className="section shell contact-section"><div className="contact-side"><span className="eyebrow">Choose the easiest way to start</span><h2>Message directly, send an email, or leave the project context below.</h2><div className="contact-channel-grid"><a className="contact-channel whatsapp" href="https://wa.me/923255504461" target="_blank" rel="noreferrer"><MessageCircle/><span><b>WhatsApp</b><small>Chat directly about your project</small></span><ArrowRight/></a><a className="contact-channel" href="mailto:hello@fahaddev.com"><Mail/><span><b>Email</b><small>Send a project brief</small></span><ArrowRight/></a></div><div className="contact-points"><p><CheckCircle2/><span><b>Send the context.</b> What you have, what is not working and what result matters.</span></p><p><CheckCircle2/><span><b>I’ll identify the likely path.</b> That may be a focused fix, an improvement pass or a larger build.</span></p><p><CheckCircle2/><span><b>Scope comes before commitment.</b> Deliverables and priorities are made clear before work begins.</span></p></div><div className="contact-direct"><Clock3/><div><b>Typical response</b><span>Within 24 hours</span></div></div></div>
<form className="contact-form" action="mailto:hello@fahaddev.com" method="post" encType="text/plain"><span className="eyebrow">Project context</span><h3>Give me enough detail to make the first reply useful.</h3><div className="form-two"><label>Name<input name="name" required placeholder="Your name"/></label><label>Email<input name="email" type="email" required placeholder="you@company.com"/></label></div><label>What needs to work better?<select name="project"><option>New e-commerce / website</option><option>Dashboard or internal tool</option><option>Full-stack web app</option><option>Fix or improve an existing product</option><option>Quick technical work</option><option>Not sure yet</option></select></label><label>Project size<select name="budget"><option>Prefer to discuss after scope</option><option>Small focused job</option><option>Medium project</option><option>Larger build</option></select></label><label>What is happening now?<textarea name="message" rows={7} placeholder="What do you have today, what is the problem, and what would a good result look like?" required/></label><button className="btn" type="submit">Send Project Context <ArrowRight size={17}/></button></form></section></Reveal></>}
