import type {Metadata} from 'next';
import {projects} from '@/lib/projects';
import {ProjectCard} from '@/components/ProjectCard';
import {PageHero} from '@/components/PageHero';
import Link from 'next/link';
import {ArrowRight, CheckCircle2, Target, Layers3, Rocket} from 'lucide-react';
import {Reveal} from '@/components/Reveal';
export const metadata:Metadata={title:'Selected Work — Product Systems Built for Real Use',description:'Commerce, dashboard and platform work focused on user decisions, business workflows and production delivery.'};
export default function Work(){return <><PageHero kind="work" eyebrow="Selected product systems" title="Work designed around the decision a customer or team needs to make next." body="A closer look at commerce, dashboard, and platform builds — the problem behind each one, the system underneath it, and the outcome the experience was designed to support." secondary="See What I Build" secondaryHref="/services"/><Reveal><section className="section shell"><div className="portfolio-intro"><div><span className="eyebrow">How I evaluate a build</span><h2>Not by how many screens it has. By whether the system makes the important path clearer.</h2></div><ul><li><Target/>Outcome first</li><li><Layers3/>System-level thinking</li><li><Rocket/>Production delivery</li></ul></div><div className="project-grid project-grid-wide">{projects.map(p=><ProjectCard key={p.slug} p={p}/>)}</div></section></Reveal><Reveal><section className="work-proof"><div className="shell"><article><CheckCircle2/><h3>Responsive behavior</h3><p>Designed for the screens customers actually use.</p></article><article><CheckCircle2/><h3>Business-side control</h3><p>Content and admin needs considered alongside the public experience.</p></article><article><CheckCircle2/><h3>Clean deployment</h3><p>Launch, ownership, and handoff treated as part of the work.</p></article></div></section></Reveal><section className="cta-band"><div className="shell"><span className="eyebrow">Have a similar challenge?</span><h2>Your product does not need to look like these projects to benefit from the same thinking.</h2><Link className="btn light-btn" href="/contact">Get a Free Project Roadmap <ArrowRight size={17}/></Link></div></section></>}
