import Link from 'next/link';
import { ArrowRight, Check, Gauge, Database, LayoutDashboard, ShieldCheck, Workflow, Sparkles, Headphones } from 'lucide-react';
import { ProjectCard } from '@/components/ProjectCard';
import { featuredProjects } from '@/lib/projects';
import { TechVisual } from '@/components/TechVisual';
import { StackSection } from '@/components/StackSection';
import { Partners } from '@/components/Partners';
import { Testimonials } from '@/components/Testimonials';

export default function Home(){return <>
<section className="hero shell"><div className="hero-mesh"/><div className="hero-copy"><span className="eyebrow">Full-stack product development</span><h1>High-performance web systems for brands that have outgrown templates.</h1><p className="lead">Custom storefronts, dashboards, and web apps designed around the business behind them — from interface and data to payments, deployment, and handoff.</p><div className="hero-actions"><Link className="btn" href="/contact">Book a Free Project Consultation <ArrowRight size={17}/></Link><Link className="btn btn-secondary" href="/work">Explore Selected Work</Link></div><p className="microproof"><Check size={15}/> Scope agreed before build <span>·</span> Visible progress <span>·</span> Launch support included</p></div><TechVisual kind="home"/></section>
<section className="trust-strip"><div className="shell"><span>Built as one connected system</span><div className="trust-points"><b>Next.js</b><b>TypeScript</b><b>Supabase</b><b>Stripe</b><b>Sanity</b><b>Vercel</b></div></div></section>
<section className="section shell"><div className="section-head"><span className="eyebrow">What clients actually get</span><h2>Not a pile of pages. A product that is easier to trust, use, manage, and grow.</h2></div><div className="benefit-grid"><article><Gauge/><h3>Fast where it matters</h3><p>Mobile-first layouts, performance-minded architecture, and fewer unnecessary layers between a visitor and the next action.</p></article><article><Database/><h3>Control after launch</h3><p>Content and data systems designed so normal updates do not require calling a developer every time.</p></article><article><LayoutDashboard/><h3>Clarity for your team</h3><p>Interfaces shaped around real workflows so people can find information and take action without fighting the product.</p></article><article><ShieldCheck/><h3>Cleaner handoff</h3><p>Accounts, deployment, documentation, and ownership stay clear so the project is not held hostage by the build process.</p></article></div></section>
<section className="section alt"><div className="shell"><div className="section-head inline-head"><div><span className="eyebrow">Selected work</span><h2>See the thinking behind the build.</h2></div><Link className="text-link" href="/work">View the full portfolio <ArrowRight size={16}/></Link></div><div className="project-grid">{featuredProjects.map(p=><ProjectCard key={p.slug} p={p}/>)}</div><p className="honesty-note">Concept projects are labeled clearly. No invented client claims.</p></div></section>
<StackSection/>
<Partners/>
<section className="section alt"><div className="shell"><div className="section-head"><span className="eyebrow">A direct way to build</span><h2>Fewer layers between the problem, the decision, and the code.</h2></div><div className="reason-grid"><article><Workflow/><span>01</span><h3>One owner across the stack</h3><p>Frontend, backend, data, deployment, and handoff are considered together instead of being passed between disconnected people.</p></article><article><Sparkles/><span>02</span><h3>Scope before noise</h3><p>We define what matters first, then build toward outcomes instead of letting features accumulate without a reason.</p></article><article><Headphones/><span>03</span><h3>Direct communication</h3><p>Your questions go to the person building the system, so decisions do not get lost through account-management layers.</p></article><article><ShieldCheck/><span>04</span><h3>No lock-in mindset</h3><p>The goal is a product you can understand, own, and keep operating after delivery.</p></article></div></div></section>
<section className="section shell"><div className="section-head"><span className="eyebrow">How a project moves</span><h2>A clear process that flexes around the size of the work.</h2><p>No fake week-by-week promises. A quick fix and a full platform should not be forced into the same timeline.</p></div><div className="steps"><article><span>01</span><b>Understand</b><p>Goals, users, constraints, urgency, and what success should look like.</p></article><article><span>02</span><b>Shape</b><p>Scope, priorities, direction, and the right technical approach.</p></article><article><span>03</span><b>Build & review</b><p>Working increments you can see and respond to as the product takes shape.</p></article><article><span>04</span><b>Launch & hand off</b><p>QA, deployment, domain setup, ownership, and practical next steps.</p></article></div><Link className="text-link" href="/process">See the complete process <ArrowRight size={16}/></Link></section>
<Testimonials/>
<section className="section shell"><div className="guarantee"><div><span className="eyebrow">Clear before commitment</span><h2>Good projects start with fewer surprises.</h2></div><div className="guarantee-list"><p><ShieldCheck/><span><b>Scope written first.</b> You know what is being built before development starts.</span></p><p><ShieldCheck/><span><b>Progress stays visible.</b> You are not waiting until the end to discover what was made.</span></p><p><ShieldCheck/><span><b>Launch is part of delivery.</b> Deployment and handoff are treated as product work, not an afterthought.</span></p></div></div></section>
<section className="cta-band"><div className="shell"><span className="eyebrow">Start with the project, not a sales pitch</span><h2>Bring the idea, the broken workflow, or the site that needs to perform better.</h2><p>I’ll help you identify the most useful next step and whether I’m the right developer for it.</p><Link className="btn light-btn" href="/contact">Book a Free Project Consultation <ArrowRight size={17}/></Link></div></section>
</>}
