import Link from 'next/link';
import { ArrowRight, Check, Gauge, Database, LayoutDashboard, ShieldCheck, Workflow, Sparkles, Headphones, TrendingUp, MousePointerClick, Settings2, Rocket } from 'lucide-react';
import { ProjectCard } from '@/components/ProjectCard';
import { featuredProjects } from '@/lib/projects';
import { HeroImage } from '@/components/HeroImage';
import { StackSection } from '@/components/StackSection';
import { Partners } from '@/components/Partners';
import { Testimonials } from '@/components/Testimonials';
import { Reveal } from '@/components/Reveal';

export default function Home(){return <>
<section className="hero shell"><div className="hero-mesh"/><Reveal className="hero-copy"><span className="eyebrow">Full-stack web product development</span><h1>Web products built to turn attention into action — and operations into momentum.</h1><p className="lead">I design and build high-performance storefronts, dashboards, and web apps that help customers move faster, teams work cleaner, and businesses stay in control after launch.</p><div className="hero-actions"><Link className="btn" href="/contact">Get a Free Project Roadmap <ArrowRight size={17}/></Link><Link className="btn btn-secondary" href="/work">See Client Outcomes</Link></div><p className="microproof"><Check size={15}/> Clear scope before build <span>·</span> Mobile-first delivery <span>·</span> Launch and handoff included</p></Reveal><Reveal className="hero-media"><HeroImage kind="home"/></Reveal></section>
<section className="trust-strip"><div className="shell"><span>Built around outcomes, powered by</span><div className="trust-points"><b>Next.js</b><b>TypeScript</b><b>Supabase</b><b>Stripe</b><b>Sanity</b><b>Vercel</b></div></div></section>
<Reveal><section className="section shell"><div className="section-head"><span className="eyebrow">What your business gets</span><h2>A website should do more than exist. It should make the next move easier.</h2><p>The build is shaped around the outcomes your customers and team actually need — not around filling a page with features.</p></div><div className="benefit-grid"><article><MousePointerClick/><h3>More decisive customer journeys</h3><p>Clear hierarchy, stronger calls to action, and fewer dead ends between interest and conversion.</p></article><article><Gauge/><h3>Fast mobile experiences</h3><p>Responsive layouts and performance-minded implementation designed for real phones, not just desktop demos.</p></article><article><Settings2/><h3>Less day-to-day friction</h3><p>CMS, dashboards, and admin flows that reduce repetitive work and make updates easier for your team.</p></article><article><ShieldCheck/><h3>Cleaner ownership after launch</h3><p>Accounts, source, deployment, and handoff stay organized so your product is not trapped inside the build process.</p></article></div></section></Reveal>
<Reveal><section className="outcome-band"><div className="shell outcome-grid"><div><TrendingUp/><span>Customer outcome</span><b>Faster paths from interest to action.</b></div><div><LayoutDashboard/><span>Team outcome</span><b>Less digging, fewer manual steps, better visibility.</b></div><div><Database/><span>Business outcome</span><b>A product that is easier to operate and extend.</b></div><div><Rocket/><span>Launch outcome</span><b>A production-ready release with clear ownership.</b></div></div></section></Reveal>
<Reveal><section className="section alt"><div className="shell"><div className="section-head inline-head"><div><span className="eyebrow">Selected work</span><h2>Proof is easier to trust when you can see how the system was built.</h2></div><Link className="text-link" href="/work">Explore all work <ArrowRight size={16}/></Link></div><div className="project-grid">{featuredProjects.map(p=><ProjectCard key={p.slug} p={p}/>)}</div></div></section></Reveal>
<StackSection/>
<Partners/>
<Reveal><section className="section alt"><div className="shell"><div className="section-head"><span className="eyebrow">Why clients choose a direct build</span><h2>Less handoff. Faster decisions. One person responsible for the whole system.</h2></div><div className="reason-grid"><article><Workflow/><span>01</span><h3>One owner across the stack</h3><p>Interface, backend, data, deployment, and handoff are considered together instead of being split across disconnected teams.</p></article><article><Sparkles/><span>02</span><h3>Build around the business goal</h3><p>Features are prioritized by what improves the customer journey or the team workflow, not by what looks impressive in a proposal.</p></article><article><Headphones/><span>03</span><h3>Direct communication</h3><p>You speak to the person making product and technical decisions, which keeps feedback faster and clearer.</p></article><article><ShieldCheck/><span>04</span><h3>Designed for handoff</h3><p>You keep access to the code, accounts, data, and deployment path so the product remains yours.</p></article></div></div></section></Reveal>
<Reveal><section className="section shell"><div className="section-head"><span className="eyebrow">A process that adapts to the job</span><h2>Quick work can move quickly. Bigger systems get the depth they actually need.</h2><p>The steps stay clear without forcing every project into the same artificial timeline.</p></div><div className="steps"><article><span>01</span><b>Understand</b><p>Goal, users, constraints, urgency, and what success should look like.</p></article><article><span>02</span><b>Shape</b><p>Scope, priorities, technical direction, and the right first milestone.</p></article><article><span>03</span><b>Build & review</b><p>Visible working progress so feedback happens while improvements are still easy.</p></article><article><span>04</span><b>Launch & hand off</b><p>QA, deployment, domain setup, ownership, and clear next steps.</p></article></div><Link className="text-link" href="/process">See the complete process <ArrowRight size={16}/></Link></section></Reveal>
<Testimonials/>
<Reveal><section className="section shell"><div className="guarantee"><div><span className="eyebrow">A clearer way to start</span><h2>Know what is being built before the build starts.</h2></div><div className="guarantee-list"><p><ShieldCheck/><span><b>Scope written first.</b> Deliverables and priorities are agreed before development.</span></p><p><ShieldCheck/><span><b>Progress stays visible.</b> You review real working stages instead of waiting for a final reveal.</span></p><p><ShieldCheck/><span><b>Launch is part of delivery.</b> Deployment and handoff are treated as part of the product, not an afterthought.</span></p></div></div></section></Reveal>
<section className="cta-band"><div className="shell"><span className="eyebrow">Have something that needs to perform better?</span><h2>Get a practical project roadmap before you commit to the build.</h2><p>Share the goal, the current problem, or the idea. I’ll help you identify the clearest next step and the right level of build.</p><Link className="btn light-btn" href="/contact">Get a Free Project Roadmap <ArrowRight size={17}/></Link></div></section>
</>}
